apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wisecow
  name: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wisecow
    spec:
      containers:
      - image: my-wise
        name: my-wise
        resources: {}
status: {}
