name: GitHub Action WorkFlow (CI/CD)
on:
  push:
    branches:
      - main  # We can set the branch name from where we need to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: debian-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Path to your Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/your-image-name:latest           # image name is my-wise here

      - name: Kubernetes deployment Update
        if: success()
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl set image deployment/your-deployment-name \
            your-container-name=${{ secrets.REGISTRY_URL }}/your-image-name:latest \       # wisecow is deployment name in deployment.yaml
            --record

      - name: Verify deployment rollout status
        if: success()
        run: kubectl rollout status deployment/your-deployment-name
